[target.x86_64-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static"]
[target.i686-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-args=/NODEFAULTLIB:MSVCRT"]
[target.'cfg(target_os="macos")']
rustflags = [
    "-C", "link-args=-sectcreate __CGPreLoginApp __cgpreloginapp /dev/null",
]
#[target.'cfg(target_os="linux")']
# glibc-static required, this may fix https://github.com/rustdesk/rustdesk/issues/9103, but I do not want this big change
# this is unlikely to help also, because the other so files still use libc dynamically
#rustflags = [
#    "-C", "link-args=-Wl,-Bstatic -lc -Wl,-Bdynamic"
#]
[net]
git-fetch-with-cli = true

[env]
VCPKG_ROOT = { value = "D:/vcpkg" }
LIBCLANG_PATH = { value = "D:/software/DevEco Studio/sdk/default/openharmony/native/llvm/bin" }
BINDGEN_EXTRA_CLANG_ARGS_x86_64_pc_windows_msvc = { value = "--target=x86_64-pc-windows-msvc -I\"D:/software/DevEco Studio/sdk/default/openharmony/native/llvm/lib/clang/15.0.4/include\" -I\"C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.44.35207/include\" -I\"C:/Program Files (x86)/Windows Kits/10/Include/10.0.26100.0/ucrt\" -I\"C:/Program Files (x86)/Windows Kits/10/Include/10.0.26100.0/shared\" -I\"C:/Program Files (x86)/Windows Kits/10/Include/10.0.26100.0/um\" -I\"C:/Program Files (x86)/Windows Kits/10/Include/10.0.26100.0/winrt\" -I\"C:/Program Files (x86)/Windows Kits/10/Include/10.0.26100.0/cppwinrt\"", force = true }
