#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/hdesk/rustdesk /usr/bin/rustdesk
	rm -f /usr/share/applications/hdesk.desktop /usr/share/applications/hdesk-link.desktop >/dev/null 2>&1 || true

	if [ "systemd" == "$INITSYS" ]; then

		systemctl disable rustdesk >/dev/null 2>&1 || true
		rm -f /etc/systemd/system/rustdesk.service /usr/lib/systemd/system/rustdesk.service /usr/lib/systemd/user/rustdesk.service >/dev/null 2>&1 || true
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/hdesk/files/systemd/hdesk.service /usr/lib/systemd/system/hdesk.service
		# try fix error in Ubuntu 18.04
		# Failed to reload rustdesk.service: Unit rustdesk.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/rustdesk.service:10: Executable path is not absolute: pkill -f "rustdesk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/hdesk.service
		fi
		systemctl daemon-reload
		systemctl enable hdesk
		systemctl start hdesk
	fi
	if [ -x /usr/bin/update-desktop-database ]; then
		update-desktop-database >/dev/null 2>&1 || true
	fi
fi
